Metrics = c("Command being timed:",
	"User time (seconds):",
	"System time (seconds):",
	"Percent of CPU this job got:",
	"Elapsed (wall clock) time (h:mm:ss or m:ss):",
	"Average shared text size (kbytes):",
	"Average unshared data size (kbytes):",
	"Average stack size (kbytes):",
	"Average total size (kbytes):",
	"Maximum resident set size (kbytes):",
	"Average resident set size (kbytes):",
	"Major (requiring I/O) page faults:",
	"Minor (reclaiming a frame) page faults:",
	"Voluntary context switches:",
	"Involuntary context switches:",
	"Swaps:",
	"File system inputs:",
	"File system outputs:",
	"Socket messages sent:",
	"Socket messages received:",
	"Signals delivered:",
	"Page size (bytes):",
	"Exit status:")

Methods = c("Default",
	"Huang",
	"Intermodes",
	"IsoData",
	"IJ_IsoData",
	"Li",
	"MaxEntropy",
	"Mean",
	"MinError",
	"Minimum",
	"Moments",
	"Otsu",
	"Percentile",
	"RenyiEntropy",
	"Shanbhag",
	"Triangle",
	"Yen")
