#!/bin/sh
#
# scrip para avalair o desempenho de AutoCellCouner_Global_v127.ijm
#
# Mauro Morais, 2018-06-28

/usr/bin/time -v --output=/home/mauromorais/R/imgAnalysis/results/2018-06-28/run05/time_results_run05_Default.txt /home/mauromorais/Fiji.app/ImageJ-linux64 --headless -macro /home/mauromorais/R/imgAnalysis/scripts/AutoCellCounter_Global_v127.ijm 'Default' > /home/mauromorais/R/imgAnalysis/results/performance_Default.txt
/usr/bin/time -v --output=/home/mauromorais/R/imgAnalysis/results/2018-06-28/run05/time_results_run05_Huang.txt /home/mauromorais/Fiji.app/ImageJ-linux64 --headless -macro /home/mauromorais/R/imgAnalysis/scripts/AutoCellCounter_Global_v127.ijm 'Huang' > /home/mauromorais/R/imgAnalysis/results/performance_Huang.txt
/usr/bin/time -v --output=/home/mauromorais/R/imgAnalysis/results/2018-06-28/run05/time_results_run05_Intermodes.txt /home/mauromorais/Fiji.app/ImageJ-linux64 --headless -macro /home/mauromorais/R/imgAnalysis/scripts/AutoCellCounter_Global_v127.ijm 'Intermodes' > /home/mauromorais/R/imgAnalysis/results/performance_Intermodes.txt
/usr/bin/time -v --output=/home/mauromorais/R/imgAnalysis/results/2018-06-28/run05/time_results_run05_IsoData.txt /home/mauromorais/Fiji.app/ImageJ-linux64 --headless -macro /home/mauromorais/R/imgAnalysis/scripts/AutoCellCounter_Global_v127.ijm 'IsoData' > /home/mauromorais/R/imgAnalysis/results/performance_IsoData.txt
/usr/bin/time -v --output=/home/mauromorais/R/imgAnalysis/results/2018-06-28/run05/time_results_run05_IJ_IsoData.txt /home/mauromorais/Fiji.app/ImageJ-linux64 --headless -macro /home/mauromorais/R/imgAnalysis/scripts/AutoCellCounter_Global_v127.ijm 'IJ_IsoData' > /home/mauromorais/R/imgAnalysis/results/performance_IJ_IsoData.txt
/usr/bin/time -v --output=/home/mauromorais/R/imgAnalysis/results/2018-06-28/run05/time_results_run05_Li.txt /home/mauromorais/Fiji.app/ImageJ-linux64 --headless -macro /home/mauromorais/R/imgAnalysis/scripts/AutoCellCounter_Global_v127.ijm 'Li' > /home/mauromorais/R/imgAnalysis/results/performance_Li.txt
/usr/bin/time -v --output=/home/mauromorais/R/imgAnalysis/results/2018-06-28/run05/time_results_run05_MaxEntropy.txt /home/mauromorais/Fiji.app/ImageJ-linux64 --headless -macro /home/mauromorais/R/imgAnalysis/scripts/AutoCellCounter_Global_v127.ijm 'MaxEntropy' > /home/mauromorais/R/imgAnalysis/results/performance_MaxEntropy.txt
/usr/bin/time -v --output=/home/mauromorais/R/imgAnalysis/results/2018-06-28/run05/time_results_run05_Mean.txt /home/mauromorais/Fiji.app/ImageJ-linux64 --headless -macro /home/mauromorais/R/imgAnalysis/scripts/AutoCellCounter_Global_v127.ijm 'Mean' > /home/mauromorais/R/imgAnalysis/results/performance_Mean.txt
/usr/bin/time -v --output=/home/mauromorais/R/imgAnalysis/results/2018-06-28/run05/time_results_run05_MinError.txt /home/mauromorais/Fiji.app/ImageJ-linux64 --headless -macro /home/mauromorais/R/imgAnalysis/scripts/AutoCellCounter_Global_v127.ijm 'MinError' > /home/mauromorais/R/imgAnalysis/results/performance_MinError.txt
/usr/bin/time -v --output=/home/mauromorais/R/imgAnalysis/results/2018-06-28/run05/time_results_run05_Minimum.txt /home/mauromorais/Fiji.app/ImageJ-linux64 --headless -macro /home/mauromorais/R/imgAnalysis/scripts/AutoCellCounter_Global_v127.ijm 'Minimum' > /home/mauromorais/R/imgAnalysis/results/performance_Minimum.txt
/usr/bin/time -v --output=/home/mauromorais/R/imgAnalysis/results/2018-06-28/run05/time_results_run05_Moments.txt /home/mauromorais/Fiji.app/ImageJ-linux64 --headless -macro /home/mauromorais/R/imgAnalysis/scripts/AutoCellCounter_Global_v127.ijm 'Moments' > /home/mauromorais/R/imgAnalysis/results/performance_Moments.txt
/usr/bin/time -v --output=/home/mauromorais/R/imgAnalysis/results/2018-06-28/run05/time_results_run05_Otsu.txt /home/mauromorais/Fiji.app/ImageJ-linux64 --headless -macro /home/mauromorais/R/imgAnalysis/scripts/AutoCellCounter_Global_v127.ijm 'Otsu' > /home/mauromorais/R/imgAnalysis/results/performance_Otsu.txt
/usr/bin/time -v --output=/home/mauromorais/R/imgAnalysis/results/2018-06-28/run05/time_results_run05_Percentile.txt /home/mauromorais/Fiji.app/ImageJ-linux64 --headless -macro /home/mauromorais/R/imgAnalysis/scripts/AutoCellCounter_Global_v127.ijm 'Percentile' > /home/mauromorais/R/imgAnalysis/results/performance_Percentile.txt
/usr/bin/time -v --output=/home/mauromorais/R/imgAnalysis/results/2018-06-28/run05/time_results_run05_RenyiEntropy.txt /home/mauromorais/Fiji.app/ImageJ-linux64 --headless -macro /home/mauromorais/R/imgAnalysis/scripts/AutoCellCounter_Global_v127.ijm 'RenyiEntropy' > /home/mauromorais/R/imgAnalysis/results/performance_RenyiEntropy.txt
/usr/bin/time -v --output=/home/mauromorais/R/imgAnalysis/results/2018-06-28/run05/time_results_run05_Shanbhag.txt /home/mauromorais/Fiji.app/ImageJ-linux64 --headless -macro /home/mauromorais/R/imgAnalysis/scripts/AutoCellCounter_Global_v127.ijm 'Shanbhag' > /home/mauromorais/R/imgAnalysis/results/performance_Shanbhag.txt
/usr/bin/time -v --output=/home/mauromorais/R/imgAnalysis/results/2018-06-28/run05/time_results_run05_Triangle.txt /home/mauromorais/Fiji.app/ImageJ-linux64 --headless -macro /home/mauromorais/R/imgAnalysis/scripts/AutoCellCounter_Global_v127.ijm 'Triangle' > /home/mauromorais/R/imgAnalysis/results/performance_Triangle.txt
/usr/bin/time -v --output=/home/mauromorais/R/imgAnalysis/results/2018-06-28/run05/time_results_run05_Yen.txt /home/mauromorais/Fiji.app/ImageJ-linux64 --headless -macro /home/mauromorais/R/imgAnalysis/scripts/AutoCellCounter_Global_v127.ijm 'Yen' > /home/mauromorais/R/imgAnalysis/results/performance_Yen.txt

echo "-------"
echo "Finish!"
echo "-------"